#!/bin/bash

PS3='Please enter your choice: '
options=('Option 1' 'Option 2' 'Option 3' 'Quit')
select opt in "$(options[@])"
do
    case $opt in 
        'Option 1')
            nano
	    ;;
        'Option 2')
            vi
	    ;;
        'Option 3')
            links
            ;;
	'Quit')
            break
            ;;
        *) echo "option  $REPLY is invalid"
    esac
done
